### ISSUE TITLE
Add study features to broadcasts

### ISSUE THREAD

**Issue by SergioGlorias** [Siderite/lichessTools#141]
Some features of the studies are interesting for people commenting on broadcast matches

such as the numbered arrows

And it is worth remembering that each round in the broadcast is a study

**Comment by Siderite** [comment]
I've never watched a broadcast match. The problem with numbered arrows and other things is that there is a completely different mechanism working for playing game pages and analysis game pages. Much harder to do anything in playing games. There is also a "law" of lichess to not modify the playing part.

I understand you mean the spectators, not the players, but I don't know the details of these broadcasts. I will investigate.

**Comment by SergioGlorias** [comment]
I think you can explore the Word Cup part (since it's going on)
https://lichess.org/broadcast/fide-world-cup-2023-open-section/round-2-game-1/weZnNhIY

The board interface is like a study

For example, this round of the broadcast
https://lichess.org/broadcast/leca-chess-open-2023/round-3/DUSZfIpw
It represents this study
https://lichess.org/study/DUSZfIpw

Usually these games are not taking place within lichess and stockfish can be switched on

And I can even say
each round a pgn link is inserted as source with all games
and the organisers update that pgn whenever there is movement
also if the organiser asks for a delay the lichess can add it without problems.

**Comment by Siderite** [comment]
Fixed in v2.0.41
