### ISSUE TITLE
Bugs in Broadcast

### ISSUE THREAD

**Issue by SergioGlorias** [Siderite/lichessTools#144]
https://github.com/Siderite/lichessTools/assets/9739913/66ee5b49-3e86-4239-9316-80c4b9e43241

https://github.com/Siderite/lichessTools/assets/9739913/4d688e1e-2f07-40c3-8b20-940c90a7f934

**Comment by Siderite** [comment]
Are you using 2.0.41?

**Comment by Siderite** [comment]
Second video bug fixed in v2.0.42

**Comment by Siderite** [comment]
First video bug fixed in v2.0.42

**Comment by Siderite** [comment]
Thanks for reporting the bugs!
