### ISSUE TITLE
Explore free hosting for data to serve as a server component for storing data and communicating between users.

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#221]
Note that lichess will not allow calls to the outside, so this requires communication with the extension. This might also solve the chessdb.cn situation, but adds complexity to the extension that I tried to avoid, especially in view of a possible port to Firefox.

**Comment by Siderite** [comment]
https://supabase.com/ -  open source Firebase alternative ?

**Comment by Dboingue** [comment]
Are not concern for correspondance in-game.  Non-correspondance users already entertain xenophobic conceptions, like cheating can't be detected as well as for fast time controls (an adrenaline seeking excuse, is what I say :) .  Just make sure that it is known we can't use non-book type of assistance.  The lichess TOS might actually allow books not from lichess..  Anyway, just a possible concern. I am not sure, that it is warranted.

**Comment by Siderite** [comment]
One big issues here is CSP. If no outside connectivity is possible, then a communication between extension and lichess (like with a background page) and with the third  party will be necessary. I am not really ready to do this.

**Comment by Siderite** [comment]
Too complicated and problematic. Until a really good reason is there, LT should not connect to anything.
