### ISSUE TITLE
One should be able to expand/collapse variations in Analysis, too

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#250]
Perhaps with a context menu. It would conflict with bookmarks, though.

**Comment by Dboingue** [comment]
analysis=?    isn't' study chapter the ancestral archetype of all analysis modes?  I might not have enough experience yet with LT.
I also thought bookmarks would eventually or have an issue about making them collapsible.  In-game correspondance analysis, would then just have to bookmark what should be collapsible.  What other usage could there be?  Can all variation be bookmarkes.  or is there a small finite number of bookmark ids possible?. I obviously need to find where bookmarks work and how.

**Comment by Siderite** [comment]
Bookmarks work only on studies. This issue I think I will close. There is no reason to complexify the Tools -> Analysis board (Analysis) feature.
