### ISSUE TITLE
Update Pawn Structure feature

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#327]
- perhaps my moves should take precedence instead of interlacing them
- search for names for the opposing side as well and show them as `Opponent <name>` or something
- a better similarity should look for the length of the common starting string (x1), then for same values on same position after that breaks (x0.75 or more) then pawns that still have the option of getting to the position, so numeric but smaller than the named position (x0.5 or less). So X123X3XX compared to named X132XXMT will be 2*1 (length of X1) + 1*0.75 (a common X later on) + 1*0.5 (a pawn at 2 can move to 3) = 3.25/8 = 41%.
- compare with the entire structure text and go until the smallest length between the two compared strings, remove white spaces first
- add the most similar named structure to the title of the unnamed structure span and the similarity score

**Comment by Siderite** [comment]
Also search for more named pawn structures.

**Comment by Siderite** [comment]
Use fen if you can get it. getPositionFromBoard may not always work, as some users report.

**Comment by Dboingue** [comment]
> Use fen if you can get it. getPositionFromBoard may not always work, as some users report.

Where do you think you can get those.. Do you mean from chess knowledge, or ways to define pawn structure masks, a FEN.
I don't think that pawn structures are actually meant to be exact positions, they are abstractions.  But I guess from your use of the word similarity that you are already in that direction.  I am curious about the facts that you seem to have about where to get such already encoded in some form information.. Although, if you are using theis whole project as a way to keep looking at chess things, I would suggest using those from FLORES book, if not already what you are doing.  and the wikipage.

FEN or EPD.. EPD can be more abstract then FEN as it puts 2 of the FEN files into optional codes.  (well that is how I understand it).

I might be out of my depth here about what you are already doing. I did not have time to test this.. But I think it would be a great way to learn about how precise such notions are or to what extent each is meant to be equally specifying about all the 16 pawns in presence.

have you tried to define for yourself or for the code project some tentative automatisable definitions of pawn structure?

You are venturing into chess here not just lichess UI..   But I guess that was part of the motivation.. Kudos. and wish you success.   I will keep following this.

**Comment by Siderite** [comment]
Implemented in v2.2.2. The getPositionFromBoard thing has to be solved in another issue.
