### ISSUE TITLE
Multi browser support

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#34]
Since the extension has turned into a glorified script and style injector, adapting LiChess Tools for other browsers might be trivial. I would still need help from people using said browsers. 

I use Brave, which is a version of Chrome. Edge is a version of Chrome. What else is there? Firefox? Safari? I don't like them, so how could I test them properly?

**Comment by SergioGlorias** [comment]
I don't have much affinity in the programming part of extensions, but I can try to help test in firefox

**Comment by SergioGlorias** [comment]
By the way, if you want to launch the `.xpi` file first before publishing https://addons.mozilla.org also works

**Comment by Siderite** [comment]
The problem is with the content_scripts manifest property. While Firefox seems to support Manifest V3, it doesn't support the "world" setting which allows a script to be loaded in the context of the web page. I will have to research how to manage this in FF.

**Comment by Siderite** [comment]
adding dubious tag because Firefox has 1.5% of browser share as opposed to Chrome+Edge which is 65%. I had no idea Firefox is so lame. :)

**Comment by Siderite** [comment]
I will not do it. Firefox is small and stupid and Safari asks me for money.

**Comment by KeatsPeeks** [comment]
For future Mac users who come across this issue and are looking into Safari compatibility: you should know, you can convert Chrome extensions to Safari extensions using Xcode on your Mac (no developer account needed). Just Google it and follow the instructions. Also, remember to enable unsigned extensions in Safari.

**Comment by Siderite** [comment]
New developments make this a possibility. Firefox version implemented in v2.3.141
