### ISSUE TITLE
add shift+click feature for Copy branch as PGN

### ISSUE THREAD

**Issue by dsoul20** [Siderite/lichessTools#358]
There's a great feature with the bookmark / split chapter here to shift+click delete the chapter moves and put them in a new chapter.

Can you do something similar for the Copy branch as PGN?

E.g., add a shift+click feature to delete the branch moves and paste them in a new chapter?

Thanks, D

**Comment by Siderite** [comment]
shift-click already does something.

**Comment by Siderite** [comment]
I thought about it and copying to clipboard while deleting the moves would be too accident prone. There is no way to undo it.
