### ISSUE TITLE
hide / minimize boxes in interactive lesson mode or alternatively create shortcut to switch between normal analysis and interactive lesson mode

### ISSUE THREAD

**Issue by dsoul20** [Siderite/lichessTools#360]
In the interactive lesson mode, several boxes appear on the right which are annoying and I never use.  And also prevent me from being able to see the lines near the top right and the databases on the bottom right at one time without having to scroll down.  

Including:

You may reflect on the player's correct move, with a comment; or leave empty to jump immediately to the next move.
Add variation moves to explain why specific other moves are wrong.
When any other wrong move is played:
Explain why all other moves are wrong

Can you hide / minimize the boxes?

Alternatively, can you create a keyboard shortcut for toggling between the normal analysis and the interactive lesson?  Which would do the trick for me if I could switch back and forth quickly.  

Thanks, D

**Comment by Siderite** [comment]
You could close those with a custom CSS style. I don't think this would be a tool a lot of people would use.

I can try to implement the quick switch.
