### ISSUE TITLE
User request: command for "skipping" a move as a variation in analysis

### ISSUE THREAD

**Issue by Frederico-Messa** [Siderite/lichessTools#385]
When studying a complex endgame or attacking position, in order to understand why a move should be played by the defender side, it is usually a good start to understand what would happen if they instead have passed their move. Sometimes, we will verify that they would lose faster by not parring some threat. Other times, we will verify that they would indeed rather pass the move and that the position is a zugzwang.

Of course, there is a "show threat" feature in Lichess Analysis, but I think it would be better if we could put the moves on the board. One reason for that is that sometimes the position we arrive at by passing a move is not really trivial, and we would still like to manually check some of its sub-variants. Another reason is that sometimes we need to pass more than one move to see the main threat, which will require a lot of work to be achieved if the defender doesn't pass moves.

I think it would be nice if lichessTools allowed the user to pass the move with some configurable key shortcut and somehow created some variation with that.

I think a possible way of doing this, if Lichess does not directly allow variants that simply pass the move, is to use BFS to find a sequence of moves that reaches the same position with reversed players' turns, and then hide the intermediate sequence of moves in the UI.

**Comment by Siderite** [comment]
Let me see if I understand what you mean. You want that somehow, in the analysis phase of a position, have the option to skip the current move as a variation in the resulting move tree?

**Comment by Frederico-Messa** [comment]
> Let me see if I understand what you mean. You want that somehow, in the analysis phase of a position, have the option to skip the current move as a variation in the resulting move tree?

Yes!

**Comment by Siderite** [comment]
Assuming there are enough pieces, I can create a list of five moves that reaches the same position with the playing side reversed. There are positions where this would be impossible, but they should be edge. Once the moves are generated, you also want them somehow "hidden" from the list, though. Which is kind of weird.

**Comment by Siderite** [comment]
Is it something that you do a lot manually and you would like automatized?

**Comment by Frederico-Messa** [comment]
> Assuming there are enough pieces, I can create a list of five moves that reaches the same position with the playing side reversed. There are positions where this would be impossible, but they should be edge. Once the moves are generated, you also want them somehow "hidden" from the list, though. Which is kind of weird.

Hiddening them is not essential, but it would be neater.

> Is it something that you do a lot manually and you would like automatized?

That is what I currently do when I want to analyze such positions. But what I would rather have is to simply press a key for that.

**Comment by Siderite** [comment]
Would a command do? like you would type /skipMove and press Enter.

**Comment by Frederico-Messa** [comment]
> Would a command do? like you would type /skipMove and press Enter.

Yes.

**Comment by Siderite** [comment]
OK, will work on it.

**Comment by Frederico-Messa** [comment]
> OK, will work on it.

Thank you!

**Comment by Siderite** [comment]
Implemented in v2.3.1
