### ISSUE TITLE
Add a Help button to the PGN Editor

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#396]
it should just point to the User Manual for the PGN Editor

I think it should look like the close button, with a ? instead of an x

**Comment by Lichessisbest** [comment]
Nice idea I don`t realy understnd the PGN editor (btw I am Kostsov_Sasha)

**Comment by Siderite** [comment]
OK, here are some use cases:

**1. you want to combine several games into a single PGN**
Why? Because you want to prepare for a match against a specific opponent or you want to learn to play chess like a specific player (see the Play like... studies from me and DSoul20) or you want to study an opening

How you do it: you download the games you want (maybe you filter them out to be just with a specific variation or just a specific player, etc. (this cannot be done in the PGN Editor yet, but can be done in a text editor like Notepad++). Then you paste them in the PGN Editor and press Merge. The result is just one PGN with all the games as variations. Now you can create an Interactive Lesson in Studies and (with the LiChess Tools Extended Interactive Lesson) you test your play on all the paths.

**2. You already have a complex PGN, but you want to separate it into two main variations.** 
You can already do that with LiChess Tools in study, where you can copy whichever part of the PGN, delete it, split it into a new chapter, etc. But PGN Editor is more of a text processor, so you do it differently.

How you do it: You load the PGN in PGN Editor and you press Split. Now all different variations are split into one path games. Now you copy paste that into a text editor and you search for a specific pattern (for example the Mark feature of Notepad++ is very good for that) and you split the text file into two parts.

Now you can go back to PGN Editor, take each part and Merge them back.

**3. You have a complex PGN from your favorite opening, but you are annoyed that for the same position, reached in different ways, you get different moves (or they are duplicated)**

With LiChess Tools you already see the transpositions in the Analysis and Study move tree and also you see the moves that start from the same position, but in a different variation, but again, PGN Editor is more of a text editor.

How you do it: you copy the PGN in the PGN Editor and press Normalize. Now all the moves made from a specific position will only be part of the PGN at the first occurrence of that position. Imagine something like:
`1.e4 e5 2.d4 h5` and `1.d4 e5 2.e4 a5`. These two games reach the same position at ply 3 (after the second White move), but in the first game Black played h5, and in the second a5. If you Merge and Normalize, both moves will be made from the main line (1.e4 e5 2.d4 ...)

I hope I was clear. More in the LiChess Tools User Manual. Being a developer, I suck at making manuals, so give me a little break  there :)

**Comment by Siderite** [comment]
Implemented in v2.3.6

**Comment by Siderite** [comment]
Part of https://github.com/Siderite/lichessTools/issues/210
