### ISSUE TITLE
bug - adds a second empty chapter

### ISSUE THREAD

**Issue by dsoul20** [Siderite/lichessTools#424]
When I copy a branch as PGN and paste into a new chapter, it's been adding a second empty chapter which I then have to delete.  Started doing this last night.

-D

**Comment by Siderite** [comment]
Yeah, it's a Lichess bug. They fixed it: https://github.com/lichess-org/lila/issues/14598

**Comment by Biranidun** [comment]
Still broken for me. Uploaded a game PGN as a chapter and turned it into 50+ chapters!

**Comment by Siderite** [comment]
I said they fixed it, not that they deployed it :D Anyway, there is nothing I can do.
