### ISSUE TITLE
User Request: Add an option to select what image you want for every chess piece

### ISSUE THREAD

**Issue by Pawnstreetblues** [Siderite/lichessTools#427]
Hi, currently I use the Custom Chess Pieces tool for this but I have run into some problems with it.  Could you add this functionality to your tool?

**Comment by Siderite** [comment]
LiChess Tools is not a style enhancing extension. There are others that cover that niche. I try to stay away from anything graphical. Can't you raise the issue with the Custom Chess Pieces developer?
