### ISSUE TITLE
User request: Copy PGN from FEN position chapter (empty or not)

### ISSUE THREAD

**Issue by Dboingue** [Siderite/lichessTools#428]
Currently one has to have move object for the mouse context menu to offer "Copy PGN" of the chapter.

But lichess drawings can be had over empty board, or FEN that contains not enough critters for lichess to let them be moved

Pawn structures abstractions, and 2 kings on board.  They can't be moved. Other important teaching cases of exemplars  would all have move less chapters.  And drawings would still be valuable in PGN form. (also ability to use the local resources better than the server resources bottleneck but here, this is just bonus)..

So, is it possible within LT to allow mouse context menu click inside the visual container where usual would stand at least a move object?
or other.  perhaps context menu on board could capture the FEN and its other dumpable lichess internal data such as drawings.

Is that clear enough presentation of the request?  (not kidding).  It may amount to a Copy FEN request  but with all the decorations included.

**Comment by Siderite** [comment]
You can achieve this by using the /copypgn command (see https://siderite.dev/blog/lichess-tools---user-manual/#commands ) but opening the context menu for the empty node when there are no moves also sounds intriguing.

**Comment by Siderite** [comment]
Implemented in v2.3.14, as an option to Extra context menu options
