### ISSUE TITLE
User request: easy access button to fullscreen

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#666]
Add a button (and not a keyboard shortcut) for desktop only that when pressed makes the lichess header disappear and also puts the browser in fullscreen mode. 

To revert to normal, mouseover to top-right corner to make a button visible that does that.

**Comment by Siderite** [comment]
Implemented in v2.3.100

**Comment by pawndini** [comment]
Because the nature of my disability, it's much easier to click a button that it is to press a key on my keyboard.  So I really like this addition!  Great job!
