### ISSUE TITLE
User request: clicking an empty square where only a single piece could legally move to should perform that move

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#667]
Some concerns:
- this changes the way the game is played (it should at least have options to enable this separately for games and analysis)
- messing with how chessground works might be difficult
- this should only work in standard chess variant, as rules may be different

**Comment by Siderite** [comment]
Rather than reinventing Chessground, I raised an issue to see if there is a positive response: https://github.com/lichess-org/chessground/issues/305.

On hold for now.

**Comment by Siderite** [comment]
Implemented in v2.3.101 in Analysis/Study only (for now)

**Comment by Siderite** [comment]
Follow through with the feature natively on Lichess...

**Comment by pawndini** [comment]
FWIW, no need for variants to be included, and probably only needed in studies with interactive mode enabled.

**Comment by Siderite** [comment]
It's fine. The way Lichess does it is instruct chessground which moves are valid.

**Comment by Siderite** [comment]
Closing this. If Lichess want to implement the native one click, it will take a long time.
