### ISSUE TITLE
Show some sort of indicator showing the win/loss ratio against the current opponent

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#672]
This might take into account just the last N games or everything in the crosstable. Or even replace it completely and show it on mouseover.

**Comment by pawndini** [comment]
I know it doesn't showed the win loss ratio, but if you hover over your opponents username it does show the number of W/D/Ls that you have against that opponent.  I'm certain you are aware of this though 😺

**Comment by Siderite** [comment]
Pointless feature. LiChess Tools is not here to add fancy social visuals.
