### ISSUE TITLE
User request: add a chess quote on the lobby page

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#825]
An example source: https://www.chess.com/forum/view/general/300--chess-quotes

**Comment by Siderite** [comment]
More:
https://www.brainyquote.com/topics/chess-quotes
https://web.archive.org/web/20150219174346/http://www.chessquotes.com/

**Comment by dcraig327** [comment]
this maybe a slick way todo a quote:

the octopus on the bottom right: [https://lichess.org/study/N2EKUVGZ/10asxAEx](https://lichess.org/study/N2EKUVGZ/10asxAEx)


no not the octopus, but the oval-shaped caption above its mantle. that may feel natural to people. plus the layout is already there for the taking.

**Comment by Siderite** [comment]
https://www.azquotes.com/quotes/topics/chess.html

**Comment by Siderite** [comment]
Implemented in v2.3.152
