### ISSUE TITLE
User request: add board coordinates to the better exported image

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#847]
See the default image output:
![image](https://github.com/user-attachments/assets/edc7fb47-ecd8-4a48-8153-cb49c623d403)

**Comment by Siderite** [comment]
Maybe use shift or something like that to not have them in the image.

**Comment by fncll** [comment]
That makes sense!

**Comment by Siderite** [comment]
Implemented in v2.3.153

**Comment by fncll** [comment]
I'm opening this back up because there's something strange going on with the coordinates in the exported board now. See attached example. Notice how the files are lettered?

![FGbmQuVZ](https://github.com/user-attachments/assets/8292c6a8-e669-4ce5-9f6e-62539cc41eb2)

**Comment by Siderite** [comment]
Those are files enhanced by LiChess Tools. Soon the ranks will also increase in value, like everything else. ;D

Fixed in v2.3.158
