### ISSUE TITLE
Spaced Repetition does not accept correct moves

### ISSUE THREAD

**Issue by derpafist** [Siderite/lichessTools#880]
When there are multiple moves in the pgn for your color spaced repetition only allows one of them and will mark all others as a mistake. This is especially annoying when the move it wants you to play is a mistake marked as such. And I since this is the intended practice to cover incorrect moves in the lesson, this occurs regularly.

**Comment by Siderite** [comment]
I am aware of the limitations. That's why that feature is the only one marked as WIP. I plan to remake it, but I need some time. Spaced repetition requires much more attention than the small hack I implemented there.

**Comment by derpafist** [comment]
I mean I know nothing but in cases where your alternative move is marked with an inaccuracy or a mistake etc. would it be possible to simply exclude those from the variations that the program cycles through?
Independend from this, when there are really two good moves and you want to train both lines, there is maybe a way to communicate to the user which move(s) is not supposed to be played this time.

**Comment by Siderite** [comment]
There is, isn't it? The Solution button. If it shows arrows for all variations, then that's a bug.

**Comment by derpafist** [comment]
> There is, isn't it? The Solution button. If it shows arrows for all variations, then that's a bug.

There is a solution button. But it spoils the solution and counts as a mistake. If you want to force the player to play a particular variation, you need to instead tell him, which alternatives not to play.

**Comment by Siderite** [comment]
I understand the frustration, because you have a normal Interactive lesson and you get a single "correct" line that you marked as wrong and in your view should not be rehearsed, but Extended Interactive mode is defined by "all moves in the PGN are good".

I could create a separate "flow" setting besides sequential and spaced repetition that will never include lines with "negative" glyphs. Would that be a solution for now?

**Comment by Siderite** [comment]
As for the "preview" idea, in which you first see what the line is and then play it. Doesn't that defeat the purpose?

These are not puzzles. No one counts your success on the server. If you show the solution, yes, it marks as failed, but next time it does not.

**Comment by Siderite** [comment]
Well, with Spaced Repetition it will not choose the same line, isn't it? Hmm...
I could have a button to show the solution as a PGN only at the first move. But that would tempt people quite a lot.

**Comment by derpafist** [comment]
> I understand the frustration, because you have a normal Interactive lesson and you get a single "correct" line that you marked as wrong and in your view should not be rehearsed, but Extended Interactive mode is defined by "all moves in the PGN are good".
> 
> I could create a separate "flow" setting besides sequential and spaced repetition that will never include lines with "negative" glyphs. Would that be a solution for now?

Yes, when there are not multiple good moves that you want to train, which should be the norm, I think this is a great solution.

**Comment by derpafist** [comment]
> As for the "preview" idea, in which you first see what the line is and then play it. Doesn't that defeat the purpose?
> 
> These are not puzzles. No one counts your success on the server. If you show the solution, yes, it marks as failed, but next time it does not.

This is not what I meant. I meant in the case of multiple good moves A, B, C when SR wants you to play A, it could prompt you to not play B or C but still let you find A.

**Comment by Siderite** [comment]
So when you ask for a hint, instead of saying "N possible solutions" which I guess it's wrong if it's Spaced Rep or Sequential 😓 , you would have "One solution that is not B and C" ?

**Comment by derpafist** [comment]
> So when you ask for a hint, instead of saying "N possible solutions" which I guess it's wrong if it's Spaced Rep or Sequential 😓 , you would have "One solution that is not B and C" ?

Yes, that is my idea.

**Comment by Siderite** [comment]
Thanks for the feedback and suggestions. I will implement them when I get some time.

**Comment by Siderite** [comment]
Supplanted by https://github.com/Siderite/lichessTools/issues/882
