### ISSUE TITLE
Spaced repetition can hardly decide on first move

### ISSUE THREAD

**Issue by derpafist** [Siderite/lichessTools#903]
On 2.3.165 when I preview a lesson while avoiding bad lines and the computer has the first move, it plays 2-6 moves in a row always undoing them and saying "try again" before it finally settles on one move. Is this him trying deleted or bad lines and only realizing that after he played?

**Comment by derpafist** [comment]
It the same time a probably related problem appeared: All the lines that were green with multiple days of repeat time went red within a few hours. When I repeat, I get a bit of green progress, but it very quickly disappears again.

**Comment by Siderite** [comment]
Try now (v2.3.166)

**Comment by derpafist** [comment]
Nice
