### ISSUE TITLE
HTML5 Gamepad API integration

### ISSUE THREAD

**Issue by ddugovic** [Siderite/lichessTools#92]
This isn't urgent https://github.com/lichess-org/lila/issues/9860

> Can we please add Xbox controller support?
> There is an HTML5 Gamepad API available that could help with this.

**Comment by Siderite** [comment]
Thanks for the suggestion, but I do not own a gamepad :) I couldn't possibly test it. Or is there an emulator somewhere?

**Comment by Siderite** [comment]
Can you provide me with a mapping between controller actions and lichess actions? Maybe I can code it and you can test it.

**Comment by Siderite** [comment]
No help received. I won't fix this.
