### ISSUE TITLE
Menu overlap

### ISSUE THREAD

**Issue by derpafist** [Siderite/lichessTools#922]
![Screenshot_2024-11-17-14-10-23-031_org mozilla firefox](https://github.com/user-attachments/assets/afe5102c-4a5e-4403-9812-d322a7c00a54)

The menu is covering the Bullet, Lobby and Correspondence tabs on Firefox.

**Comment by Siderite** [comment]
Uh-oh! It's introduced by the Daily quote tool. Disable it until I fix this.

**Comment by Siderite** [comment]
fixed in v2.3.170
