### ISSUE TITLE
Click puzzle rating takes me to my profile

### ISSUE THREAD

**Issue by y1z** [Siderite/lichessTools#931]
When going to the profile of someone else and clicking on their puzzle rating it takes me back to MY profile 
![image](https://github.com/user-attachments/assets/d42ac950-c426-429f-9841-fdcbe9e12828)

**Comment by Siderite** [comment]
This should be logged at https://github.com/lichess-org/lila/, it's not something LiChess Tools does.

**Comment by y1z** [comment]
> This should be logged at https://github.com/lichess-org/lila/, it's not something LiChess Tools does.

OK will do

**Comment by y1z** [comment]
This was not the right place to put the bug report

**Comment by y1z** [comment]
Here is the appropriate bug report https://github.com/lichess-org/lila/issues/16511
