### ISSUE TITLE
Style the extension popup

### ISSUE THREAD

**Issue by Siderite** [Siderite/lichessTools#99]
The extension popup has no functionality other than to contain some links and show you the extension version, but it may be the first contact of a new user with LiChess Tools. It should look better.

**Comment by PratikMbade** [comment]
assign me this issue i want to work on it.

**Comment by Siderite** [comment]
Wow! Thanks a lot. Consider yourself assigned.

**Comment by Siderite** [comment]
Any news?

**Comment by Siderite** [comment]
Removed assignment for inactivity.

**Comment by Siderite** [comment]
Done in v2.0.41
